### ISSUE TITLE
如何使用blackbox-export监控带账号密码认证的service服务

### ISSUE THREAD

**Issue by tianxinliang123** [yunlzheng/prometheus-book#10]
k8s集群中，使用blackbox-export监控带账号密码认证的service服务，不太会用，有没有例子？

**Comment by yunlzheng** [comment]
原生支持的http_basic认证，如下：

```
http_basic_auth_example:
    prober: http
    timeout: 5s
    http:
      method: POST
      headers:
        Host: "login.example.com"
      basic_auth:
        username: "username"
        password: "mysecret"
```

如果不支持http basic，也可以考虑在headers中传递token之类的方式。

**Comment by tianxinliang123** [comment]
我的blackbox.yml的配置：如下
```
modules: 
  http_basic_auth_eureka:
    prober: http
    timeout: 50s
    http:
      preferred_ip_protocol: "ip4"
      #valid_status_codes: [200,301]
      method: POST
      headers:
        Host: "192.168.11:11:8888"
        Cache-Control: no-cache
        #Content-Type: application/xhtml+xml
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
      basic_auth:
        username: 'eureka'
        password: '********'
```
浏览器输入http://192.168.11.10:9115/probe?module=http_basic_auth_eureka&target=192.168.11.11:8888&debug=true
返回的结果
```
Logs for the probe:
ts=2018-10-14T13:44:05.812604029Z caller=main.go:116 module=http_basic_auth_eureka target=192.168.11.11:8889 level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2018-10-14T13:44:05.812991876Z caller=utils.go:42 module=http_basic_auth_eureka target=192.168.11.11:8889 level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2018-10-14T13:44:05.813048814Z caller=utils.go:65 module=http_basic_auth_eureka target=192.168.11.11:8889 level=info msg="Resolved target address" ip=192.168.11.11
ts=2018-10-14T13:44:05.813133583Z caller=http.go:282 module=http_basic_auth_eureka target=192.168.11.11:8889 level=info msg="Making HTTP request" url=http://192.168.11.11:8889 host=192.168.11:11:8888
ts=2018-10-14T13:44:05.815049201Z caller=http.go:300 module=http_basic_auth_eureka target=192.168.11.11:8889 level=info msg="Received HTTP response" status_code=400
ts=2018-10-14T13:44:05.815126856Z caller=http.go:315 module=http_basic_auth_eureka target=192.168.11.11:8889 level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=400
ts=2018-10-14T13:44:05.815197566Z caller=http.go:354 module=http_basic_auth_eureka target=192.168.11.11:8889 level=info msg="Response timings for roundtrip" roundtrip=0 start=2018-10-14T21:44:05.81340103+08:00 dnsDone=2018-10-14T21:44:05.81340103+08:00 connectDone=2018-10-14T21:44:05.813792176+08:00 gotConn=2018-10-14T21:44:05.813820583+08:00 responseStart=2018-10-14T21:44:05.814958826+08:00 end=2018-10-14T21:44:05.815028447+08:00
ts=2018-10-14T13:44:05.815457064Z caller=main.go:129 module=http_basic_auth_eureka target=192.168.11.11:8889 level=error msg="Probe failed" duration_seconds=0.00269175
```

返回的http code 为400，我的username和password是正确了，那里出问题了？大佬
